#!/bin/bash

# copy .bed files from flare results (directory 7) to sailor directory

scp *.bed /N/slate/emierdma/GSF2848/sailor

# copy WS275 files to sailor directory

scp c.elegans.WS275.annotation.final.bed /N/slate/emierdma/GSF2848/sailor

scp c_elegans.PRJNA13758.WS275.canonical_geneset.gtf /N/slate/emierdma/GSF2848/sailor

scp annotator.sailor.py emierdma@carbonate.uits.iu.edu:/N/slate/emierdma/GSF2848/sailor

# in slate sailor directory, install pybedtools (only need to do once)

conda install -c bioconda pybedtools

y

# run annotation

python3 annotator.sailor.py -h

python3 annotator.sailor.py --gtf c_elegans.PRJNA13758.WS275.canonical_geneset.gtf --fwd GSF2848-EE-N2.merged.bam.fwd.readfiltered.formatted.varfiltered.snpfiltered.ranked.bed  --rev GSF2848-EE-N2.merged.bam.rev.readfiltered.formatted.varfiltered.snpfiltered.ranked.bed  --wb c.elegans.WS275.annotation.final.bed --o /N/slate/emierdma/GSF2848/results/flare_results/N2.FLAREannotated.sites.csv
