#!/bin/bash
#in GSF2848 directory
mkdir sailor

#sailor directory should contain
      merged bamfile (GSF2848-EE-N2.merged.bed
      bedfile (c.elegans.WS275.snps.nostrand.sorted.bed)
      workflow_sailor directory containing scripts and Snakefile

#create a .json file (on text editor) with the following contents (I saved it as GSF2848-N2.json):
{
  "samples_path": "/N/slate/emierdma/GSF2848/sailor"
  "samples": [
    "GSF2848-EE-N2.merged.bam"             
  ],
  "reverse_stranded": true,
  "reference_fasta": "/N/slate/emierdma/GSF2848/genome/assembly.fasta",
  "known_snps": "/N/slate/emierdma/GSF2848/c.elegans.WS275.snps.nostrand.sorted.bed",
  "edit_type": "AG"
  "output_dir": "/N/slate/emierdma/GSF2848/results/flare_results"
}

#copy .json file to carbonate
scp GSF2848-N2.json /N/slate/emierdma/GSF2848/sailor

#make all workflow_sailor scrips executable
chmod +x filename

#in GSF2848/results
mkdir flare_results

#in interactive terminal
#in sailor directory
#load singularity every single time you run SAILOR
module load singularity

#use the following command to run SAILOR. under "--singularity-args --'bind' you will have to give access to every single directory that has relevant files
snakemake --snakefile /N/slate/emierdma/GSF2848/sailor/workflow_sailor/Snakefile --configfile /N/slate/emierdma/GSF2848/sailor/GSF2848-N2.json --use-singularity --singularity-args '--bind /N/slate/emierdma/GSF2848 --bind /N/slate/emierdma/GSF2848/genome --bind /N/slate/emierdma/GSF2848/sailor/workflow_sailor/scripts --bind /N/slate/emierdma/GSF2848/sailor/workflow_sailor --bind /N/slate/emierdma/GSF2848/results/flare_results' -j1
