#!/bin/bash
# in Carbonate- install Miniconda3 (only need to do this once)

wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh

bash Miniconda3-latest-Linux-x86_64.sh

# install sra-tools (only need to do this once)

conda install -c bioconda sra-tools

# Enter slate directory

cd /N/slate/emierdma

# create GSF2848 directory

mkdir GSF2848

# create rnaseq environment (only need to do this once)

conda create -n rnaseq -c conda-forge -c bioconda entrez-direct sra-tools==2.6.9 fastqc seqtk star samtools subread

# if sra-tools fails, use conda list to figure out what version of sra-tools you have and adjust code accordingly

# activate environment

conda activate rnaseq

# navigate to project space

cd /N/project/HundleyLab

# enter GSF2848 directory

cd GSF2848

# copy files to your own GSF2848 directory

scp GSF2848-EE* emierdma@carbonate.uits.iu.edu:/N/slate/emierdma/GSF2848

# navigate back to your directory

cd /N/slate/emierdma/GSF2848

# unzip files

gunzip GSF2848*

# proceed to alignment
